name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Test of Action-setup-swift
    steps:
    - name: Install Swift.
      uses: YOCKOW/Action-setup-swift@development-1.0.x
      with:
        swift-version: '5.1'
    - name: View Swift Version
      run: swift --version
    - uses: actions/checkout@master
    - name: Run Swift
      run: cd swift-package-for-test && swift test
